### ISSUE TITLE
Agregar formulario de captura de la info de la tienda

### ISSUE THREAD

**Issue by crmock** [EstebanDalelR/CovidTenderos#12]
Se debe reemplazar el formulario de google drive por un formulario más amigable visualmente. esto puede seguir dejando la info en google sheets pero debe estar alineado al look an feel de la página

**Comment by EstebanDalelR** [comment]
https://forms.gle/GwbsL9iGXV9YpQYo9
Por ahora el form es de un verde parecido al de la página.
