### ISSUE TITLE
Mapa de google maps tiene altura fija de 750px debería ser dinámica

### ISSUE THREAD

**Issue by crmock** [EstebanDalelR/CovidTenderos#5]
El  mapa de google está alojado en el contenedor de la derecha de un layout de 2  columnas. Se debe corregir la hoja de estilos para que la altura del contenedor de google maps sea dinámica e igual a la altura del contenedor de la columna de la izquierda.

**Comment by EstebanDalelR** [comment]
https://github.com/pideenlaesquina/landing/pull/2

**Comment by EstebanDalelR** [comment]
@crmock
